version: '3.9'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  backend:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=${MYSQL_USER}
      - DB_DATABASE=${MYSQL_DATABASE}
    volumes:
      - './backend:/app'
    depends_on:
      - mariadb

  frontend:
    build: ./front
    ports:
      - '4200:4200'
    volumes:
      - './front:/app'
      - '/app/node_modules'
    working_dir: /app

volumes:
  mariadb_data:
